# Common config, all service need it.
eureka.client.serviceUrl.defaultZone: http://localhost:6111/eureka/
management.security.enabled: false
management.context-path: /monitor
security:
    sessions: stateless

# Logging config.
# logging.level.org.springframework: debug

# Service config.
spring.application.name: sec-service
server.port: 6263

xtoken.authKey: Lippolis
